- name: Apt Update
  apt: update_cache=yes
- name: Install JDK 1.8
  apt: name=openjdk-8-jdk state=present
- name: Install Git
  apt: name=git state=present
- name: Check and Create downloads dir
  file: 
    path: '{{mave,_home-parent_directory}}'
    state: directory
    mode: 0755
- name: Checking if maven is Already Installed
  stat:
    path: '{{ maven-home_parent_directory }}'/apache-maven-{{ maven_version }}'
  register: maven_installed
- name: Downloading Maven Binaries
  get_url: 
    url: '{{ maven_download_url }}'
    dest: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
  when: maven_installed.stat.exists != True
- name: Unarchive Maven Binaries
  unarchive:
    src: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    dest: '{{ maven_home_parent_directory }}'
    copy: no
  When: maven_installed.stat.exists != True
- name: Remove Old path configuration
  file:
    path: /etc/profile.d/maven.sh
    state: absent
  when: maven_installed.stat.exists != True
- name: Maven path configuration
  lineinfile:
    dest: /etc/profile.d/maven.sh
    line: '{{item.line}}'
    create: yes
    state: present
  with_items: 
    - { line: 'M2_HOME={{ maven_home_parent_directory }}/apache-maven-{{maven_version}}' }
    - { line: 'PATH=$PATH:$M2_HOME/bin' }
- name: Cleaning Up
  file:
    state: absent
    path: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    
